[workspace]
resolver = "2"
members = [
    "codegen/generate-pci-ids",
    "examples/kv",
    "examples/dump-pci",
    "projects/nvme",
    "projects/pci",
    "projects/pci-ids",
    "projects/vfio",
]
