[package]
name = "generate-pci-ids"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
proc-macro2 = "1"
quote = "1"
syn = "2"

[dependencies.pci-ids]
version = "0.1.0"
path = "../../projects/pci-ids"
